/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package employeemanagement;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author admin
 */
public class deleteemployee extends javax.swing.JFrame {

    Connection conn=null;
        PreparedStatement pst=null;
        ResultSet rs=null;
    /**
     * Creates new form deleteemployee
     */
    public deleteemployee() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        address = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        Join_date = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        search = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        designation = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        age = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        salary = new javax.swing.JTextField();
        contact = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        emp_id = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButton2.setText("BACK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(387, 426, 90, 23);

        jLabel10.setText("8. EMAIL ID ");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(114, 339, 166, 14);
        getContentPane().add(address);
        address.setBounds(290, 271, 173, 20);

        jLabel7.setText("9. emp_id");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(114, 370, 63, 14);
        getContentPane().add(Join_date);
        Join_date.setBounds(290, 214, 173, 20);

        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        getContentPane().add(name);
        name.setBounds(290, 119, 173, 20);

        search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchKeyPressed(evt);
            }
        });
        getContentPane().add(search);
        search.setBounds(658, 144, 109, 20);

        jLabel5.setText("1.  NAME OF EMPLOYEE");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(114, 122, 134, 14);

        jLabel4.setText("4. COMPANY JOINT DATE");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(114, 216, 134, 16);
        getContentPane().add(designation);
        designation.setBounds(290, 245, 173, 20);

        jButton1.setText("Delete");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(283, 426, 80, 23);
        getContentPane().add(age);
        age.setBounds(290, 150, 173, 20);

        jLabel3.setText("3.  SALARY OF  EMPLOYEES");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(114, 184, 134, 19);

        jLabel9.setText("7. MOBILE NO.");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(114, 308, 166, 14);

        salary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salaryActionPerformed(evt);
            }
        });
        getContentPane().add(salary);
        salary.setBounds(290, 182, 173, 20);
        getContentPane().add(contact);
        contact.setBounds(290, 302, 173, 20);

        jLabel1.setFont(new java.awt.Font("AR DELANEY", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("EMPLOYEE  MANAGEMENT  -  DELETE MENU");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 42, 851, 51);

        jLabel2.setText("2.  AGE OF  EMPLOYEE");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(114, 151, 134, 21);

        jLabel6.setText("5.  DESIGNATION ");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(114, 246, 166, 14);

        jLabel11.setText("Enter Emp Id to delete");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(658, 112, 166, 14);
        getContentPane().add(emp_id);
        emp_id.setBounds(290, 364, 173, 20);

        jLabel8.setText("6. ADDRESS");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(114, 274, 166, 14);
        getContentPane().add(email);
        email.setBounds(290, 333, 173, 20);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(-10, 0, 900, 500);

        setSize(new java.awt.Dimension(808, 488));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void searchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchKeyPressed
        try{
            conn=(Connection) DriverManager.getConnection("jdbc:ucanaccess://J:\\employeemanagement.accdb");
            String sql= "select name,emp_id, age, designation, address, contact, salary, Join_date, email from employee where emp_id=?";
            pst=(PreparedStatement) conn.prepareStatement(sql);
            pst.setString(1,search.getText());

            rs=pst.executeQuery();
            if(rs.next())
            {
                String add1=rs.getString("name");
                name.setText(add1);

                String add2=rs.getString("age");
                age.setText(add2);

                String add3=rs.getString("designation");
                designation.setText(add3);

                String add4=rs.getString("address");
                address.setText(add4);

                String add5=rs.getString("contact");
                contact.setText(add5);

                String add6=rs.getString("salary");
                salary.setText(add6);

                String add7=rs.getString("Join_date");
                Join_date.setText(add7);

                String add8=rs.getString("email");
                email.setText(add8);

                String add9=rs.getString("emp_id");
                emp_id.setText(add9);
            }

        }catch(SQLException e){}

    }//GEN-LAST:event_searchKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{
        conn=(Connection) DriverManager.getConnection("jdbc:ucanaccess://J:\\employeemanagement.accdb");
        String sql = "DELETE from employee WHERE emp_id=?";
        
        pst=(PreparedStatement) conn.prepareStatement(sql);
        pst.setString(1,emp_id.getText());
        pst.executeUpdate();
        JOptionPane.showMessageDialog(null,"Deleted Successfully....");
        }
        catch(SQLException e){
        JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void salaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_salaryActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        mainmenu m =new mainmenu();
        m.setVisible(true);
        this.hide();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(deleteemployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(deleteemployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(deleteemployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(deleteemployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new deleteemployee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Join_date;
    private javax.swing.JTextField address;
    private javax.swing.JTextField age;
    private javax.swing.JTextField contact;
    private javax.swing.JTextField designation;
    private javax.swing.JTextField email;
    private javax.swing.JTextField emp_id;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField name;
    private javax.swing.JTextField salary;
    private javax.swing.JTextField search;
    // End of variables declaration//GEN-END:variables
}
