/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package employeemanagement;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author admin
 */
public class updateemployee extends javax.swing.JFrame {

    Connection conn=null;
        PreparedStatement pst=null;
        ResultSet rs=null;
    /**
     * Creates new form updateemployee
     */
    public updateemployee() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        age = new javax.swing.JTextField();
        salary = new javax.swing.JTextField();
        Join_date = new javax.swing.JTextField();
        designation = new javax.swing.JTextField();
        address = new javax.swing.JTextField();
        contact = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        search = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        emp_id = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel5.setText("1.  NAME OF EMPLOYEE");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(114, 81, 150, 14);

        jLabel2.setText("2.  AGE OF  EMPLOYEE");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(114, 109, 134, 21);

        jLabel3.setText("3.  SALARY OF  EMPLOYEE");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(114, 142, 150, 19);

        jLabel4.setText("4. COMPANY JOINT DATE");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(114, 174, 134, 16);

        jLabel6.setText("5.  DESIGNATION ");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(110, 200, 170, 14);

        jLabel8.setText("6. ADDRESS");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(114, 227, 166, 14);

        jLabel9.setText("7. MOBILE NO.");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(114, 258, 166, 14);

        jLabel10.setText("8. EMAIL ID ");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(114, 295, 166, 14);

        jLabel11.setText("Enter Emp Id");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(620, 150, 166, 14);

        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        getContentPane().add(name);
        name.setBounds(290, 80, 173, 20);
        getContentPane().add(age);
        age.setBounds(290, 110, 173, 20);

        salary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salaryActionPerformed(evt);
            }
        });
        getContentPane().add(salary);
        salary.setBounds(290, 140, 173, 20);
        getContentPane().add(Join_date);
        Join_date.setBounds(290, 170, 173, 20);
        getContentPane().add(designation);
        designation.setBounds(290, 200, 173, 20);
        getContentPane().add(address);
        address.setBounds(290, 230, 173, 20);
        getContentPane().add(contact);
        contact.setBounds(290, 260, 173, 20);
        getContentPane().add(email);
        email.setBounds(290, 290, 173, 20);

        search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchKeyPressed(evt);
            }
        });
        getContentPane().add(search);
        search.setBounds(600, 180, 140, 30);

        jLabel1.setFont(new java.awt.Font("AR DELANEY", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("EMPLOYEE  MANAGEMENT  -  UPDATE MENU");
        jLabel1.setToolTipText("");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 851, 51);

        jButton1.setText("Update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(257, 390, 100, 23);

        jLabel7.setText("9.EMP_ ID");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(114, 320, 90, 30);
        getContentPane().add(emp_id);
        emp_id.setBounds(290, 330, 170, 20);

        jButton2.setText("BACK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(390, 390, 100, 23);
        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 0, 10, 10);
        getContentPane().add(jPanel2);
        jPanel2.setBounds(10, 10, 10, 10);
        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 0, 890, 440);

        setSize(new java.awt.Dimension(941, 477));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void salaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_salaryActionPerformed

    private void searchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchKeyPressed
try{
    conn=(Connection) DriverManager.getConnection("jdbc:ucanaccess://J:\\employeemanagement.accdb");
           String sql= "select * from employee where emp_id=?";
           pst=(PreparedStatement) conn.prepareStatement(sql);
                   pst.setString(1,search.getText());
                   
                   rs=pst.executeQuery();
                   if(rs.next())
                   {
                       String add1=rs.getString("name");
                       name.setText(add1);
                       
                       String add2=rs.getString("age");
                       age.setText(add2);
                       
                       String add3=rs.getString("designation");
                       designation.setText(add3);
                       
                       String add4=rs.getString("address");
                       address.setText(add4);
                       
                       String add5=rs.getString("contact");
                       contact.setText(add5);
                       
                       String add6=rs.getString("salary");
                       salary.setText(add6);
                       
                       String add7=rs.getString("Join_date");
                       Join_date.setText(add7);
                       
                       String add8=rs.getString("email");
                       email.setText(add8);
                       
                       String add9=rs.getString("emp_id");
                       emp_id.setText(add9);
                   }
                   
       }catch(SQLException e){}
        

    }//GEN-LAST:event_searchKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{
        conn=(Connection) DriverManager.getConnection("jdbc:ucanaccess://J:\\employeemanagement.accdb");
        String sql="UPDATE employee SET name=?, age=?, designation=?, address=?, contact=?, salary=?, Join_date=?, email=? WHERE emp_id=?";
        
        pst=(PreparedStatement) conn.prepareStatement(sql);
        pst.setString(1,name.getText());
        pst.setString(2,age.getText());
        pst.setString(3,designation.getText());
        pst.setString(4,address.getText());
        pst.setString(5,contact.getText());
        pst.setString(6,salary.getText());
        pst.setString(7,Join_date.getText());
        pst.setString(8,email.getText());
        pst.setString(9,emp_id.getText());
        pst.executeUpdate();
        JOptionPane.showMessageDialog(null,"Updated Successfull....");
        }
        catch(SQLException e){
        JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        mainmenu m =new mainmenu();
        m.setVisible(true);
        this.hide();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(updateemployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(updateemployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(updateemployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(updateemployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new updateemployee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Join_date;
    private javax.swing.JTextField address;
    private javax.swing.JTextField age;
    private javax.swing.JTextField contact;
    private javax.swing.JTextField designation;
    private javax.swing.JTextField email;
    private javax.swing.JTextField emp_id;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField name;
    private javax.swing.JTextField salary;
    private javax.swing.JTextField search;
    // End of variables declaration//GEN-END:variables
}
